# Generated by Django 4.2.2 on 2024-02-23 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('birth_date', models.DateField(blank=True, default=None, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('picture', models.ImageField(blank=True, default='uploads/profile_pictures/default.png', upload_to='uploads/profile_pictures/')),
                ('sex', models.CharField(default=None, max_length=10, null=True)),
                ('weight_unit', models.CharField(choices=[('lbs', 'Pounds'), ('kg', 'Kilograms')], default='kg', max_length=3)),
                ('body_weight', models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True)),
                ('pb_bench', models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True)),
                ('pb_deadlift', models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True)),
                ('pb_pullups', models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True)),
                ('pb_pushups', models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True)),
                ('pb_planktime', models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True)),
                ('pb_squat', models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True)),
                ('pb_miletime', models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True)),
                ('pb_5ktime', models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True)),
                ('daily_streak', models.PositiveIntegerField(default=0)),
                ('fitness_interests', models.CharField(blank=True, choices=[('weightlifting', 'Weightlifting'), ('running', 'Running'), ('cycling', 'Cycling'), ('swimming', 'Swimming'), ('yoga', 'Yoga')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
