# Generated by Django 4.2.2 on 2024-02-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_workout'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='type',
            field=models.CharField(blank=True, choices=[('weightlifting', 'Weightlifting'), ('running', 'Running'), ('cycling', 'Cycling'), ('swimming', 'Swimming'), ('yoga', 'Yoga')], max_length=20, null=True),
        ),
    ]
