# Generated by Django 4.2.2 on 2024-02-23 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_workout_duration_workout_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gym.userprofile'),
        ),
    ]
