# Generated by Django 4.2.2 on 2024-02-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_workout_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='fitness_interests',
            field=models.CharField(blank=True, choices=[('weightlifting', 'Weightlifting'), ('running', 'Running'), ('cycling', 'Cycling'), ('swimming', 'Swimming'), ('climbing', 'Climbing'), ('yoga', 'Yoga')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='type',
            field=models.CharField(blank=True, choices=[('weightlifting', 'Weightlifting'), ('running', 'Running'), ('cycling', 'Cycling'), ('swimming', 'Swimming'), ('climbing', 'Climbing'), ('yoga', 'Yoga')], max_length=20, null=True),
        ),
    ]
