# Generated by Django 4.2.2 on 2024-02-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_alter_userprofile_fitness_interests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='type',
            field=models.CharField(blank=True, choices=[('weightlifting', 'Weightlifting'), ('running', 'Running'), ('cycling', 'Cycling'), ('swimming', 'Swimming'), ('climbing', 'Climbing'), ('rowing', 'Rowing'), ('combat', 'Combat'), ('yoga', 'Yoga')], max_length=20, null=True),
        ),
    ]
