# Generated by Django 4.2.2 on 2024-03-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0010_alter_userprofile_pb_pullups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pb_squat',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True),
        ),
    ]
